### PR TITLE
Update to Minecraft 1.20.1

### LINKED ISSUE #10: Crash on 1.19.4
```

Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:946)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.class_2588.<init>(java.lang.String, java.lang.Object[])'
	at net.mision_thi.nbttooltips.tooltips.TooltipChanger.Main(TooltipChanger.java:25)
	at net.minecraft.class_1799.handler$coc000$nbttooltips$injectEditTooltipmethod(class_1799.java:4161)
	at net.minecraft.class_1799.method_7950(class_1799.java:834)
	at net.minecraft.class_481.method_25409(class_481.java:754)
	at net.minecraft.class_465.method_2380(class_465.java:179)
	at net.minecraft.class_481.method_25394(class_481.java:743)
	at net.minecraft.class_437.method_47413(class_437.java:121)
	at net.minecraft.class_757.method_3192(class_757.java:937)
	... 6 more
```

### LINKED ISSUE #12: doesn't work on 1.19.4
Pressing "shift" does not provide any information. Most likely the mod supports 1.19.4

### PR DESCRIPTION
**Pull request by TheLukeGuy**
Tested and everything works fine!

Fixes #10
Fixes #12

### CODE REVIEW

**Comment by xmorose** [comment]
Tested it. Works!

Warped approval✅

**Comment by Boy0000** [comment]
@TheLukeGuy any interest in bumping this to 1.20?
I seem to be unable to compile it to do so, might be my lack of knowledge of mods

**Comment by TheLukeGuy** [comment]
> @TheLukeGuy any interest in bumping this to 1.20?

Sure! I'll try to update it tonight or tomorrow :)

**Comment by TheLukeGuy** [comment]
@Boy0000 Updated to 1.20.1 (though it *should* work fine on 1.20 as well) in the latest commit. :D

Here's a JAR file for anyone who doesn't want to compile from source: https://drive.google.com/file/d/1M4Jan3-fkB-xsktQ0m63PaFAxBKPVYXg/view?usp=sharing

File: src/main/resources/assets/nbttooltips/lang/en_us.json [hunk 1]
```diff
@@ -1,4 +1,4 @@
 {
   "nbttooltips.keybind": "Show NBT",
-  "item.nbt_tags.nbttooltips": "NBT: %s"
-}
\ No newline at end of file
+  "item.nbt_tags.nbttooltips": "NBT: "
```
Comment (MisionThi) [inline src/main/resources/assets/nbttooltips/lang/en_us.json:3]: May I ask why you removed the "%s"?

**Comment by MisionThi** [comment]
I'm gone test your update in a bit, thank you for helping out! @TheLukeGuy

**Comment by Boy0000** [comment]
Works fine on my end 👍 
image

**Review by MisionThi — APPROVED** [review]

File: src/main/resources/assets/nbttooltips/lang/en_us.json (hunk 1 above)
Comment (TheLukeGuy) [reply src/main/resources/assets/nbttooltips/lang/en_us.json:3]: In `TooltipChanger.java`, a `MutableText` instance is created and all of the text components that make up the NBT are just appended to that instead of ever using that translation string as a format string. So when I tested it out, there was a literal "%s" in the NBT tooltip. I have no idea how it ever worked before without that literal "%s" being there, but I'm guessing that maybe Minecraft changed the way that unused format arguments are handled or something. Or maybe I'm dumb and you did provide an argument for that `%s` in some other way that I don't know of?

Comment (MisionThi) [reply src/main/resources/assets/nbttooltips/lang/en_us.json:3]: Thank you for the explanation :)
